import { describe, it, expect, vi, beforeEach } from "vitest";
import { render, screen, fireEvent, within } from "@testing-library/react";
import { UnitCatalog } from "@/components/admin/UnitCatalog";
import { LanguageProvider } from "@/context/LanguageContext";
import en from "@/i18n/en";
import ar from "@/i18n/ar";

const swr = vi.hoisted(() => ({ list: undefined as unknown, price: undefined as unknown }));
vi.mock("swr", () => ({
  default: (key: string) => ({
    data: key.endsWith("/price") ? swr.price : swr.list,
    error: undefined, isLoading: false, isValidating: false, mutate: vi.fn(),
  }),
}));
vi.mock("@/lib/api-client", () => ({ apiFetcher: vi.fn(), uploadFile: vi.fn(), api: { post: vi.fn(), patch: vi.fn(), delete: vi.fn() } }));

const stamps = { created_at: "2026-09-05T10:00:00Z", updated_at: "2026-09-05T10:00:00Z" };
const LIST = {
  items: [
    { ...stamps, id: "c1", code: "FN-COIN-K21-0001", name_en: "Lira Rashadi", name_ar: "ليرة رشادية", karat: "K21", weight_grams: 7.2, markup_per_gram: 0.5, margin_mode: "USD", margin_value: 5, on_hand_qty: 3, min_stock_qty: 5, photo_url: null, is_active: true },
    { ...stamps, id: "c2", code: "FN-COIN-K22-0002", name_en: "English Sovereign", name_ar: "", karat: "K22", weight_grams: 7.988, markup_per_gram: -0.25, margin_mode: "PERCENT", margin_value: 2.5, on_hand_qty: 0, min_stock_qty: null, photo_url: "https://img.example/c2.jpg", is_active: false },
  ],
  total: 2, page: 1, page_size: 100,
};
const PRICE = { type_id: "c1", code: "FN-COIN-K21-0001", gold_rate_24k: 100, effective_rate: 88, metal_value: 633.6, margin_amount: 5, final_price: 638.6, on_hand_qty: 3, rate_source: "goldapi", rate_is_stale: true };
// Codes, names and the rate source come from the database: data, left as stored in either language.
const DATA = ["FN-COIN-K21-0001", "FN-COIN-K22-0002", "Lira Rashadi", "English Sovereign", "goldapi"];

function renderCatalog(lang: "en" | "ar", resource: "coins" | "ounces" = "coins") {
  // The caller still passes English nouns; the catalog must not use them.
  const nouns = resource === "coins" ? { singular: "Coin Type", plural: "Coin Types" } : { singular: "Ounce Type", plural: "Ounce Types" };
  return render(
    <LanguageProvider initialLang={lang}>
      <UnitCatalog resource={resource} adjustmentTarget={resource === "coins" ? "COIN_STOCK" : "OUNCE_STOCK"} {...nouns} />
    </LanguageProvider>,
  );
}
const firstButton = (name: string) => screen.getAllByRole("button", { name })[0];

/** The field a label names, checked both ways: by its text and through label.control. */
function expectLabelled(text: string) {
  const control = screen.getByLabelText(text);
  const label = control.closest("label") as HTMLLabelElement;
  expect(label, text).not.toBeNull();
  expect(label.control, text).toBe(control);
  return control;
}
function expectEveryControlNamed(count: number) {
  const controls = Array.from(document.querySelectorAll<HTMLInputElement | HTMLSelectElement>("input, select, textarea"));
  expect(controls.length).toBe(count);
  for (const control of controls) {
    expect(control.labels?.length || control.getAttribute("aria-label"), control.outerHTML).toBeTruthy();
  }
}

/** Everything a user reads or hears: text nodes plus placeholder, title, aria-label and alt. */
function uiStrings(): string[] {
  const out: string[] = [];
  const walker = document.createTreeWalker(document.body, NodeFilter.SHOW_TEXT);
  while (walker.nextNode()) out.push(walker.currentNode.textContent ?? "");
  document.body.querySelectorAll("*").forEach((el) => {
    for (const attr of ["placeholder", "title", "aria-label", "alt"]) {
      const value = el.getAttribute(attr);
      if (value) out.push(value);
    }
  });
  return out.map((s) => s.trim()).filter(Boolean);
}
/** A run of two or more Latin letters is a word; "K21" and "/g" are not. Data is set aside first. */
const hasEnglishWord = (s: string) => /[A-Za-z]{2,}/.test(DATA.reduce((rest, datum) => rest.split(datum).join(""), s));

beforeEach(() => {
  swr.list = LIST;
  swr.price = PRICE;
});

describe("UnitCatalog labels (NEX-64)", () => {
  it("every field in the new-type form is reachable by its label", () => {
    renderCatalog("en");
    fireEvent.click(screen.getByRole("button", { name: en.unitCatalog.coins.newType }));
    const u = en.unitCatalog;
    for (const text of [u.karat, en.common.nameEn, en.common.nameAr, u.weightG, u.markupPerGram, u.marginMode, u.marginUsd, u.minStockQty]) {
      expectLabelled(text);
    }
    // A new type has no code yet: a heading and a note, not a label pointing at nothing.
    expect(screen.queryByLabelText(u.code)).toBeNull();
    expect(screen.getByText(u.autoGenerated)).toBeInTheDocument();
    // The hidden file input is named after the section it belongs to.
    expect(screen.getByLabelText(u.photo, { selector: "input" })).toHaveAttribute("type", "file");
    expectEveryControlNamed(11);
  });

  it("the margin label follows the margin mode and keeps hold of its input", () => {
    renderCatalog("en");
    fireEvent.click(screen.getByRole("button", { name: en.unitCatalog.coins.newType }));
    const input = screen.getByLabelText(en.unitCatalog.marginUsd);
    fireEvent.change(screen.getByLabelText(en.unitCatalog.marginMode), { target: { value: "PERCENT" } });
    expect(expectLabelled(en.unitCatalog.marginPercent)).toBe(input);
  });

  it("the edit form labels the read-only code", () => {
    renderCatalog("en");
    fireEvent.click(firstButton(en.common.edit));
    const code = expectLabelled(en.unitCatalog.code);
    expect(code).toBeDisabled();
    expect(code).toHaveValue("FN-COIN-K21-0001");
    expect(screen.getByRole("button", { name: en.unitCatalog.saveChanges })).toBeInTheDocument();
  });

  it("every field in the stock-adjust dialog is reachable by its label", () => {
    renderCatalog("en");
    fireEvent.click(firstButton(en.unitCatalog.adjustStock));
    for (const text of [en.unitCatalog.deltaQty, en.unitCatalog.reason, en.unitCatalog.notes]) expectLabelled(text);
    // The hint sits beside the label, not inside it, so it stays out of the field's name.
    expect(screen.getByLabelText(en.unitCatalog.deltaQty)).toHaveAccessibleName(en.unitCatalog.deltaQty);
    expectEveryControlNamed(5);
  });

  it("names the search box, the filter, the icon-only buttons and the empty header cells", () => {
    renderCatalog("ar");
    const u = ar.unitCatalog;
    expect(screen.getByLabelText(u.coins.search)).toHaveAttribute("placeholder", u.coins.search);
    expectLabelled(u.includeInactive);
    for (const name of [u.livePrice, u.adjustStock, ar.common.edit]) {
      expect(screen.getAllByRole("button", { name }), name).toHaveLength(2);
    }
    expect(screen.getByRole("button", { name: u.deactivate })).toBeInTheDocument();
    expect(screen.getByRole("button", { name: u.reactivate })).toBeInTheDocument();
    expect(screen.getByRole("columnheader", { name: u.photo })).toBeInTheDocument();
    expect(screen.getByRole("columnheader", { name: ar.common.actions })).toBeInTheDocument();
  });
});

describe("UnitCatalog in Arabic (NEX-64)", () => {
  it("leaves no English behind — list and new-type form", () => {
    renderCatalog("ar");
    fireEvent.click(screen.getByRole("button", { name: ar.unitCatalog.coins.newType }));
    for (const english of ["New Coin Type", "Include inactive", "Code", "Name", "Karat", "Weight", "Markup / Margin", "On hand", "Min", "inactive", "auto-generated", "Name (English)", "Weight (g)", "Markup / g (±)", "Margin mode", "Flat USD", "Percent", "Margin (USD)", "Min stock qty", "Photo", "Upload photo", "Create Coin Type", "Cancel"]) {
      expect(screen.queryByText(english), english).toBeNull();
    }
    expect(screen.queryByPlaceholderText("Search coin types…")).toBeNull();
    expect(screen.queryByPlaceholderText("(none)")).toBeNull();
    expect(uiStrings().filter(hasEnglishWord)).toEqual([]);
  });

  it("leaves no English behind — edit form, with a photo", () => {
    renderCatalog("ar");
    fireEvent.click(screen.getAllByRole("button", { name: ar.common.edit })[1]);
    expect(screen.getByText(ar.unitCatalog.coins.editType)).toBeInTheDocument();
    expect(screen.getByRole("img", { name: ar.unitCatalog.photoPreview })).toBeInTheDocument();
    expect(screen.getByRole("button", { name: ar.unitCatalog.removePhoto })).toHaveAttribute("title", ar.unitCatalog.removePhoto);
    expect(screen.getByRole("button", { name: ar.unitCatalog.changePhoto })).toBeInTheDocument();
    expect(screen.getByRole("button", { name: ar.unitCatalog.saveChanges })).toBeInTheDocument();
    expect(uiStrings().filter(hasEnglishWord)).toEqual([]);
  });

  it("leaves no English behind — stock-adjust dialog", () => {
    renderCatalog("ar");
    fireEvent.click(firstButton(ar.unitCatalog.adjustStock));
    for (const english of ["Adjust stock", "Delta (qty)", "Whole numbers only.", "Reason", "CORRECTION", "THEFT", "Notes", "Apply", "Cancel"]) {
      expect(screen.queryByText(english), english).toBeNull();
    }
    expect(screen.getByLabelText(ar.unitCatalog.deltaQty)).toHaveAttribute("placeholder", ar.unitCatalog.deltaPlaceholder);
    expect(screen.getByLabelText(ar.unitCatalog.notes)).toHaveAttribute("placeholder", ar.unitCatalog.notesPlaceholder);
    expect(screen.getByRole("option", { name: ar.unitCatalog.reasons.THEFT })).toHaveValue("THEFT");
    expect(uiStrings().filter(hasEnglishWord)).toEqual([]);
  });

  it("leaves no English behind — live price dialog", () => {
    renderCatalog("ar");
    fireEvent.click(firstButton(ar.unitCatalog.livePrice));
    for (const english of ["Live price", "per unit", "Spot 24K", "Effective rate", "Metal value", "Margin", "On hand", "Source", "(stale)", "Close"]) {
      expect(screen.queryByText(english, { exact: false }), english).toBeNull();
    }
    const u = ar.unitCatalog;
    expect(screen.getByText(u.effectiveRate).parentElement).toHaveTextContent(`$88.00/g ${u.markupApplied}`);
    expect(screen.getByText(u.source).parentElement).toHaveTextContent(`goldapi${u.stale}`);
    expect(screen.getByRole("button", { name: ar.common.close })).toBeInTheDocument();
    expect(uiStrings().filter(hasEnglishWord)).toEqual([]);
  });

  it("uses the ounce wording for the ounce catalog, whatever nouns the caller passes", () => {
    swr.list = { items: [], total: 0, page: 1, page_size: 100 };
    renderCatalog("ar", "ounces");
    const o = ar.unitCatalog.ounces;
    expect(screen.getByText(o.empty)).toBeInTheDocument();
    expect(screen.getByPlaceholderText(o.search)).toBeInTheDocument();
    fireEvent.click(screen.getByRole("button", { name: o.newType }));
    expect(screen.getByRole("button", { name: o.createType })).toBeInTheDocument();
    expect(uiStrings().filter(hasEnglishWord)).toEqual([]);
  });

  it("keeps codes, signed rates and karats left-to-right inside Arabic text", () => {
    renderCatalog("ar");
    expect(screen.getByText("+0.5000/g").closest("bdi")).toHaveAttribute("dir", "ltr");
    expect(screen.getByText("-0.2500/g").closest("bdi")).toHaveAttribute("dir", "ltr");
    expect(screen.getAllByText("FN-COIN-K21-0001")[0]).toHaveClass("font-mono");

    fireEvent.click(firstButton(ar.unitCatalog.adjustStock));
    // The subtitle sits in a font-mono box: the phrase carries the UI direction, the code stays LTR.
    const phrase = document.querySelector(".font-mono > span[dir]") as HTMLElement;
    expect(phrase).toHaveAttribute("dir", "rtl");
    expect(phrase).toHaveTextContent(`FN-COIN-K21-0001 · ${ar.unitCatalog.onHandInline} 3`);
    expect(within(phrase).getByText("FN-COIN-K21-0001").closest("bdi")).toHaveAttribute("dir", "ltr");

    fireEvent.click(firstButton(ar.unitCatalog.livePrice));
    expect(screen.getByText(new RegExp(ar.unitCatalog.perUnit))).toHaveTextContent(`${ar.unitCatalog.perUnit} · K21`);
  });
});

describe("UnitCatalog in English is unchanged", () => {
  it("keeps the list, form and dialog copy the screen had before the strings moved", () => {
    renderCatalog("en");
    expect(screen.getByPlaceholderText("Search coin types…")).toBeInTheDocument();
    expect(screen.getByText("+0.5000/g").closest("div")).toHaveTextContent("± +0.5000/g");
    expect(screen.getByText("inactive")).toBeInTheDocument();

    fireEvent.click(screen.getByRole("button", { name: "New Coin Type" }));
    expect(screen.getByRole("button", { name: "Create Coin Type" })).toBeInTheDocument();
    fireEvent.click(firstButton("Edit"));
    expect(screen.getByText("Edit Coin Type")).toBeInTheDocument();

    fireEvent.click(firstButton("Adjust stock"));
    const phrase = document.querySelector(".font-mono > span[dir]") as HTMLElement;
    expect(phrase).toHaveAttribute("dir", "ltr");
    expect(phrase).toHaveTextContent("FN-COIN-K21-0001 · on hand 3");
    expect(screen.getByRole("option", { name: "CORRECTION" })).toBeInTheDocument();

    fireEvent.click(firstButton("Live price"));
    expect(screen.getByText(/per unit/)).toHaveTextContent("per unit · K21");
    expect(screen.getByText("Effective rate").parentElement).toHaveTextContent("$88.00/g (markup applied)");
    expect(screen.getByText("Source").parentElement).toHaveTextContent("goldapi(stale)");
    // The sweep the Arabic tests rely on does see this screen's copy.
    expect(uiStrings().filter(hasEnglishWord).length).toBeGreaterThan(40);
  });

  it("keeps the empty state and the ounce wording", () => {
    swr.list = { items: [], total: 0, page: 1, page_size: 100 };
    renderCatalog("en", "ounces");
    expect(screen.getByText("No ounce types yet")).toBeInTheDocument();
    expect(screen.getByRole("button", { name: "New Ounce Type" })).toBeInTheDocument();
    expect(screen.getByPlaceholderText("Search ounce types…")).toBeInTheDocument();
  });
});

describe("unitCatalog dictionary is translated, not English placeholders", () => {
  const strings = (dict: typeof en.unitCatalog) => ({
    ...dict,
    ...Object.fromEntries(Object.entries(dict.coins).map(([k, v]) => [`coins.${k}`, v])),
    ...Object.fromEntries(Object.entries(dict.ounces).map(([k, v]) => [`ounces.${k}`, v])),
    ...Object.fromEntries(Object.entries(dict.reasons).map(([k, v]) => [`reasons.${k}`, v])),
    coins: "", ounces: "", reasons: "",
  });
  const english = strings(en.unitCatalog) as Record<string, string>;
  const arabic = strings(ar.unitCatalog) as Record<string, string>;

  it("every ar.unitCatalog string contains Arabic and differs from English", () => {
    const keys = Object.keys(english).filter((key) => english[key]);
    expect(keys.length).toBeGreaterThan(65);
    for (const key of keys) {
      expect(arabic[key], key).toMatch(/[\u0600-\u06FF]/);
      expect(arabic[key], key).not.toBe(english[key]);
    }
  });
});
